# -*- coding: utf-8 -*-
"""web_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBTek7S_x_CiSp1pWH-rTAiLEMIkDqX5
"""

import requests
import bs4

data = requests.get('https://www.checkraka.com/house/?quicksearch_order=ASC&page=1')
data

soup = bs4.BeautifulSoup(data.text)

soup

all_house = soup.find_all('div',{ 'class' : 'product-highlight-item category-44'})

for house in all_house :
    print (house.find('div',{'class' : 'mid'}).text.strip() )
    print (house.find('div',{'class' : 'card'}).text)
    print()

# import csv
# import requests
# from bs4 import BeautifulSoup

# # ฟังก์ชันดึงข้อมูลจากหน้าเว็บ
# def fetch_data_from_page(page_number):
#     url = f'https://www.checkraka.com/house/?quicksearch_order=ASC&page={page_number}'
#     response = requests.get(url)
#     soup = BeautifulSoup(response.text, 'html.parser')
#     return soup

# # เตรียม list สำหรับเก็บข้อมูล
# house_data = []

# # ดึงข้อมูลจากหน้า 1 ถึง 3
# for page in range(1, 4):
#     print(f"Fetching data from page {page}...")
#     soup = fetch_data_from_page(page)

#     # ค้นหาทุกองค์ประกอบที่เป็นบ้าน
#     all_house = soup.find_all('div', {'class': 'product-highlight-item category-44'})

#     # ดึงข้อมูลชื่อโครงการและราคา
#     for house in all_house:
#         # ค้นหาชื่อโครงการ
#         project_name = house.find('div', {'class': 'mid'}).text.strip() if house.find('div', {'class': 'mid'}) else 'N/A'

#         # ค้นหาราคา
#         price_div = house.find('div', {'class': 'card'})
#         if price_div:
#             price_text = price_div.text.strip()
#             # แยกชื่อโครงการและราคา
#             parts = price_text.split('เริ่มต้น')
#             project_name = parts[0].strip() if len(parts) > 1 else price_text
#             # ลบคำว่า "เริ่มต้น" และเก็บเฉพาะตัวเลข
#             price = parts[1].strip() if len(parts) > 1 else 'N/A'
#         else:
#             project_name = 'N/A'
#             price = 'N/A'

#         # ตรวจสอบผลลัพธ์
#         print("Project Name:", project_name)
#         print("Price:", price)
#         print()

#         house_data.append((project_name, price))

# # เขียนข้อมูลลงไฟล์ CSV โดยใช้การเข้ารหัส UTF-8 พร้อม BOM
# with open('house_data.csv', mode='w', newline='', encoding='utf-8-sig') as file:
#     writer = csv.writer(file)
#     # เขียน header
#     writer.writerow(['ชื่อโครงการ', 'ราคา'])
#     # เขียนข้อมูลบ้าน
#     writer.writerows(house_data)

# print("Data has been written to house_data.csv")

import csv
import requests
from bs4 import BeautifulSoup
import re

# ฟังก์ชันดึงข้อมูลจากหน้าเว็บ
def fetch_data_from_page(page_number):
    url = f'https://www.checkraka.com/house/?quicksearch_order=ASC&page={page_number}'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    return soup

# ฟังก์ชันจัดรูปแบบราคา
def format_price(price_text):
    # ลบคำว่า "ลบ" และแปลงเป็นตัวเลข
    def convert_to_number(match):
        number = float(match.group(1))
        return f"{int(number * 1_000_000):,}"

    price_text = re.sub(r'(\d+(\.\d+)?)\s*ลบ\.', convert_to_number, price_text)

    # หากมีช่วงราคาหลายช่วง ให้เพิ่มคอมมา
    def add_commas(match):
        return f"{int(match.group(1)):,} - {int(match.group(2)):,}"

    price_text = re.sub(r'(\d+)\s*-\s*(\d+)', add_commas, price_text)

    return price_text + " "

# เตรียม list สำหรับเก็บข้อมูล
house_data = []

# ดึงข้อมูลจากหน้า 1 ถึง 3
for page in range(1, 4):
    print(f"Fetching data from page {page}...")
    soup = fetch_data_from_page(page)

    # ค้นหาทุกองค์ประกอบที่เป็นบ้าน
    all_house = soup.find_all('div', {'class': 'product-highlight-item category-44'})

    # ดึงข้อมูลชื่อโครงการและราคา
    for house in all_house:
        # ค้นหาชื่อโครงการ
        project_name = house.find('div', {'class': 'mid'}).text.strip() if house.find('div', {'class': 'mid'}) else 'N/A'

        # ค้นหาราคา
        price_div = house.find('div', {'class': 'card'})
        if price_div:
            price_text = price_div.text.strip()
            # แยกชื่อโครงการและราคา
            parts = price_text.split('เริ่มต้น')
            project_name = parts[0].strip() if len(parts) > 1 else price_text
            # ลบคำว่า "เริ่มต้น" และเก็บเฉพาะตัวเลข
            price = parts[1].strip() if len(parts) > 1 else 'N/A'
            # จัดรูปแบบราคา
            price = format_price(price)
        else:
            project_name = 'N/A'
            price = 'N/A'

        # ตรวจสอบผลลัพธ์
        print("Project Name:", project_name)
        print("Price:", price)
        print()

        house_data.append((project_name, price))

# เขียนข้อมูลลงไฟล์ CSV โดยใช้การเข้ารหัส UTF-8 พร้อม BOM
with open('house_data.csv', mode='w', newline='', encoding='utf-8-sig') as file:
    writer = csv.writer(file)
    # เขียน header
    writer.writerow(['ชื่อโครงการ', 'ราคา'])
    # เขียนข้อมูลบ้าน
    writer.writerows(house_data)

print("Data has been written to house_data.csv")